"""Add Master Class tables

Revision ID: 1754342088
Revises: 
Create Date: 2025-08-04 21:14:48.794206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1754342088'
down_revision = None
branch_labels = ('default',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_sense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_tag', sa.String(length=100), nullable=True),
    sa.Column('meta_tag_include', sa.Boolean(), nullable=True),
    sa.Column('pub_id', sa.String(length=20), nullable=True),
    sa.Column('add_code', sa.String(length=500), nullable=True),
    sa.Column('show_ads', sa.Boolean(), nullable=True),
    sa.Column('add_leaderboard', sa.Text(), nullable=True),
    sa.Column('add_medium_rectangle', sa.Text(), nullable=True),
    sa.Column('add_large_rectangle', sa.Text(), nullable=True),
    sa.Column('add_mobile_banner', sa.Text(), nullable=True),
    sa.Column('add_wide_skyscraper', sa.Text(), nullable=True),
    sa.Column('add_skyscraper', sa.Text(), nullable=True),
    sa.Column('add_large_skyscraper', sa.Text(), nullable=True),
    sa.Column('add_billboard', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_tag',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_tag_id'), 'blog_tag', ['id'], unique=False)
    op.create_index(op.f('ix_blog_tag_name'), 'blog_tag', ['name'], unique=True)
    op.create_index(op.f('ix_blog_tag_slug'), 'blog_tag', ['slug'], unique=True)
    op.create_table('categoria',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_id'), 'categoria', ['id'], unique=False)
    op.create_table('configuracion',
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('moneda', sa.String(length=5), nullable=True),
    sa.Column('verify_user_by_email', sa.Boolean(), nullable=True),
    sa.Column('r', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracion_id'), 'configuracion', ['id'], unique=False)
    op.create_table('etiqueta',
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etiqueta_id'), 'etiqueta', ['id'], unique=False)
    op.create_table('files',
    sa.Column('archivo', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('hashtag', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_table('mail_config',
    sa.Column('MAIL_SERVER', sa.String(length=100), nullable=True),
    sa.Column('MAIL_PORT', sa.String(length=6), nullable=True),
    sa.Column('MAIL_USERNAME', sa.String(length=100), nullable=True),
    sa.Column('MAIL_PASSWORD', sa.LargeBinary(), nullable=True),
    sa.Column('MAIL_USE_TLS', sa.Boolean(), nullable=True),
    sa.Column('MAIL_USE_SSL', sa.Boolean(), nullable=True),
    sa.Column('MAIL_DEFAULT_SENDER', sa.String(length=100), nullable=True),
    sa.Column('MAIL_DEFAULT_SENDER_NAME', sa.String(length=100), nullable=True),
    sa.Column('email_verificado', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_config_id'), 'mail_config', ['id'], unique=False)
    op.create_table('pagos_config',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagos_config_id'), 'pagos_config', ['id'], unique=False)
    op.create_table('paypal_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enable', sa.Boolean(), nullable=True),
    sa.Column('sandbox', sa.Boolean(), nullable=True),
    sa.Column('paypal_id', sa.String(length=200), nullable=True),
    sa.Column('paypal_sandbox', sa.String(length=200), nullable=True),
    sa.Column('paypal_secret', sa.LargeBinary(), nullable=True),
    sa.Column('paypal_sandbox_secret', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programa',
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('texto', sa.String(length=1500), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('logo', sa.Boolean(), nullable=True),
    sa.Column('promocionado', sa.Boolean(), nullable=True),
    sa.Column('fecha_promocionado', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('codigo', name='codigo_programa_unico')
    )
    op.create_index(op.f('ix_programa_id'), 'programa', ['id'], unique=False)
    op.create_table('style',
    sa.Column('theme', sa.String(length=15), nullable=True),
    sa.Column('custom_logo', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_style_id'), 'style', ['id'], unique=False)
    op.create_table('system_info',
    sa.Column('param', sa.String(length=20), nullable=False),
    sa.Column('val', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('param')
    )
    op.create_index(op.f('ix_system_info_param'), 'system_info', ['param'], unique=False)
    op.create_table('usuario',
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('acceso', sa.LargeBinary(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('correo_electronico', sa.String(length=150), nullable=True),
    sa.Column('correo_electronico_verificado', sa.Boolean(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('titulo', sa.String(length=15), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('nacimiento', sa.Date(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('fecha_alta', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('linkedin', sa.String(length=50), nullable=True),
    sa.Column('facebook', sa.String(length=50), nullable=True),
    sa.Column('twitter', sa.String(length=50), nullable=True),
    sa.Column('github', sa.String(length=500), nullable=True),
    sa.Column('youtube', sa.String(length=500), nullable=True),
    sa.Column('portada', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo_electronico', name='correo_usuario_unico')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_usuario'), 'usuario', ['usuario'], unique=True)
    op.create_table('blog_post',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('allow_comments', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_post_author_id'), 'blog_post', ['author_id'], unique=False)
    op.create_index(op.f('ix_blog_post_id'), 'blog_post', ['id'], unique=False)
    op.create_index(op.f('ix_blog_post_slug'), 'blog_post', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_post_status'), 'blog_post', ['status'], unique=False)
    op.create_table('certificado',
    sa.Column('code', sa.String(length=11), nullable=True),
    sa.Column('titulo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.Column('css', sa.Text(), nullable=True),
    sa.Column('habilitado', sa.Boolean(), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('usuario', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificado_code'), 'certificado', ['code'], unique=True)
    op.create_index(op.f('ix_certificado_id'), 'certificado', ['id'], unique=False)
    op.create_table('programa_estudiante',
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('programa', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['programa'], ['programa.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programa_estudiante_id'), 'programa_estudiante', ['id'], unique=False)
    op.create_index(op.f('ix_programa_estudiante_programa'), 'programa_estudiante', ['programa'], unique=False)
    op.create_index(op.f('ix_programa_estudiante_usuario'), 'programa_estudiante', ['usuario'], unique=False)
    op.create_table('recurso',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('logo', sa.Boolean(), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=True),
    sa.Column('promocionado', sa.Boolean(), nullable=True),
    sa.Column('fecha_promocionado', sa.DateTime(), nullable=True),
    sa.Column('usuario', sa.String(length=20), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='codigo_recurso_unico')
    )
    op.create_index(op.f('ix_recurso_codigo'), 'recurso', ['codigo'], unique=True)
    op.create_index(op.f('ix_recurso_id'), 'recurso', ['id'], unique=False)
    op.create_table('usuario_grupo',
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('tutor', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['tutor'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_grupo_activo'), 'usuario_grupo', ['activo'], unique=False)
    op.create_index(op.f('ix_usuario_grupo_id'), 'usuario_grupo', ['id'], unique=False)
    op.create_table('blog_comment',
    sa.Column('post_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_comment_id'), 'blog_comment', ['id'], unique=False)
    op.create_index(op.f('ix_blog_comment_post_id'), 'blog_comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_blog_comment_status'), 'blog_comment', ['status'], unique=False)
    op.create_index(op.f('ix_blog_comment_user_id'), 'blog_comment', ['user_id'], unique=False)
    op.create_table('blog_post_tags',
    sa.Column('post_id', sa.String(length=26), nullable=False),
    sa.Column('tag_id', sa.String(length=26), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('curso',
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=True),
    sa.Column('descripcion_corta', sa.String(length=280), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('portada', sa.Boolean(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=9), nullable=False),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('modalidad', sa.String(length=10), nullable=True),
    sa.Column('foro_habilitado', sa.Boolean(), nullable=False),
    sa.Column('limitado', sa.Boolean(), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('promocionado', sa.Boolean(), nullable=True),
    sa.Column('fecha_promocionado', sa.DateTime(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('auditable', sa.Boolean(), nullable=True),
    sa.Column('precio', sa.Numeric(), nullable=True),
    sa.Column('certificado', sa.Boolean(), nullable=True),
    sa.Column('plantilla_certificado', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['plantilla_certificado'], ['certificado.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='curso_codigo_unico')
    )
    op.create_index(op.f('ix_curso_codigo'), 'curso', ['codigo'], unique=True)
    op.create_index(op.f('ix_curso_estado'), 'curso', ['estado'], unique=False)
    op.create_index(op.f('ix_curso_id'), 'curso', ['id'], unique=False)
    op.create_index(op.f('ix_curso_plantilla_certificado'), 'curso', ['plantilla_certificado'], unique=False)
    op.create_table('master_classes',
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description_public', sa.Text(), nullable=False),
    sa.Column('description_private', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('early_discount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('discount_deadline', sa.DateTime(), nullable=True),
    sa.Column('platform_name', sa.String(length=50), nullable=False),
    sa.Column('platform_url', sa.String(length=500), nullable=False),
    sa.Column('is_certificate', sa.Boolean(), nullable=False),
    sa.Column('diploma_template_id', sa.String(length=26), nullable=True),
    sa.Column('video_recording_url', sa.String(length=500), nullable=True),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('instructor_id', sa.String(length=150), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['diploma_template_id'], ['certificado.code'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_classes_diploma_template_id'), 'master_classes', ['diploma_template_id'], unique=False)
    op.create_index(op.f('ix_master_classes_id'), 'master_classes', ['id'], unique=False)
    op.create_index(op.f('ix_master_classes_instructor_id'), 'master_classes', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_master_classes_slug'), 'master_classes', ['slug'], unique=True)
    op.create_table('usuario_grupo_miembro',
    sa.Column('grupo', sa.String(length=26), nullable=True),
    sa.Column('usuario', sa.String(length=150), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['grupo'], ['usuario_grupo.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_grupo_miembro_id'), 'usuario_grupo_miembro', ['id'], unique=False)
    op.create_table('announcement',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('course_id', sa.String(length=10), nullable=True),
    sa.Column('created_by_id', sa.String(length=150), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_sticky', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_course_id'), 'announcement', ['course_id'], unique=False)
    op.create_index(op.f('ix_announcement_created_by_id'), 'announcement', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_announcement_id'), 'announcement', ['id'], unique=False)
    op.create_table('categoria_curso',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_curso_categoria'), 'categoria_curso', ['categoria'], unique=False)
    op.create_index(op.f('ix_categoria_curso_curso'), 'categoria_curso', ['curso'], unique=False)
    op.create_index(op.f('ix_categoria_curso_id'), 'categoria_curso', ['id'], unique=False)
    op.create_table('certificacion',
    sa.Column('usuario', sa.String(length=26), nullable=False),
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('certificado', sa.String(length=26), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nota', sa.Numeric(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['certificado'], ['certificado.code'], ),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificacion_certificado'), 'certificacion', ['certificado'], unique=False)
    op.create_index(op.f('ix_certificacion_curso'), 'certificacion', ['curso'], unique=False)
    op.create_index(op.f('ix_certificacion_id'), 'certificacion', ['id'], unique=False)
    op.create_index(op.f('ix_certificacion_usuario'), 'certificacion', ['usuario'], unique=False)
    op.create_table('coupon',
    sa.Column('course_id', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=150), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'code', name='unique_coupon_per_course')
    )
    op.create_index(op.f('ix_coupon_code'), 'coupon', ['code'], unique=False)
    op.create_index(op.f('ix_coupon_course_id'), 'coupon', ['course_id'], unique=False)
    op.create_index(op.f('ix_coupon_created_by'), 'coupon', ['created_by'], unique=False)
    op.create_index(op.f('ix_coupon_id'), 'coupon', ['id'], unique=False)
    op.create_table('curso_recurso_descargable',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('recurso', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['recurso'], ['recurso.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_recurso_descargable_curso'), 'curso_recurso_descargable', ['curso'], unique=False)
    op.create_index(op.f('ix_curso_recurso_descargable_id'), 'curso_recurso_descargable', ['id'], unique=False)
    op.create_index(op.f('ix_curso_recurso_descargable_recurso'), 'curso_recurso_descargable', ['recurso'], unique=False)
    op.create_table('curso_seccion',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('indice', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_seccion_curso'), 'curso_seccion', ['curso'], unique=False)
    op.create_index(op.f('ix_curso_seccion_id'), 'curso_seccion', ['id'], unique=False)
    op.create_index(op.f('ix_curso_seccion_indice'), 'curso_seccion', ['indice'], unique=False)
    op.create_table('curso_usuario_avance',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('recursos_requeridos', sa.Integer(), nullable=True),
    sa.Column('recursos_completados', sa.Integer(), nullable=True),
    sa.Column('avance', sa.Float(asdecimal=True), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_usuario_avance_curso'), 'curso_usuario_avance', ['curso'], unique=False)
    op.create_index(op.f('ix_curso_usuario_avance_id'), 'curso_usuario_avance', ['id'], unique=False)
    op.create_index(op.f('ix_curso_usuario_avance_usuario'), 'curso_usuario_avance', ['usuario'], unique=False)
    op.create_table('docente_curso',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docente_curso_curso'), 'docente_curso', ['curso'], unique=False)
    op.create_index(op.f('ix_docente_curso_id'), 'docente_curso', ['id'], unique=False)
    op.create_index(op.f('ix_docente_curso_usuario'), 'docente_curso', ['usuario'], unique=False)
    op.create_table('etiqueta_curso',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('etiqueta', sa.String(length=26), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['etiqueta'], ['etiqueta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_etiqueta_curso_curso'), 'etiqueta_curso', ['curso'], unique=False)
    op.create_index(op.f('ix_etiqueta_curso_etiqueta'), 'etiqueta_curso', ['etiqueta'], unique=False)
    op.create_index(op.f('ix_etiqueta_curso_id'), 'etiqueta_curso', ['id'], unique=False)
    op.create_table('foro_mensaje',
    sa.Column('curso_id', sa.String(length=10), nullable=False),
    sa.Column('usuario_id', sa.String(length=150), nullable=False),
    sa.Column('parent_id', sa.String(length=26), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['foro_mensaje.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foro_mensaje_curso_id'), 'foro_mensaje', ['curso_id'], unique=False)
    op.create_index(op.f('ix_foro_mensaje_id'), 'foro_mensaje', ['id'], unique=False)
    op.create_index(op.f('ix_foro_mensaje_parent_id'), 'foro_mensaje', ['parent_id'], unique=False)
    op.create_index(op.f('ix_foro_mensaje_usuario_id'), 'foro_mensaje', ['usuario_id'], unique=False)
    op.create_table('message_thread',
    sa.Column('course_id', sa.String(length=10), nullable=False),
    sa.Column('student_id', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['student_id'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_thread_id'), 'message_thread', ['id'], unique=False)
    op.create_table('moderador_curso',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderador_curso_curso'), 'moderador_curso', ['curso'], unique=False)
    op.create_index(op.f('ix_moderador_curso_id'), 'moderador_curso', ['id'], unique=False)
    op.create_index(op.f('ix_moderador_curso_usuario'), 'moderador_curso', ['usuario'], unique=False)
    op.create_table('pago',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('moneda', sa.String(length=5), nullable=True),
    sa.Column('monto', sa.Numeric(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('metodo', sa.String(length=20), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('audit', sa.Boolean(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo_electronico', sa.String(length=150), nullable=False),
    sa.Column('direccion1', sa.String(length=200), nullable=True),
    sa.Column('direccion2', sa.String(length=200), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pago_curso'), 'pago', ['curso'], unique=False)
    op.create_index(op.f('ix_pago_id'), 'pago', ['id'], unique=False)
    op.create_index(op.f('ix_pago_usuario'), 'pago', ['usuario'], unique=False)
    op.create_table('programa_curso',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('programa', sa.String(length=10), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['programa'], ['programa.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programa_curso_curso'), 'programa_curso', ['curso'], unique=False)
    op.create_index(op.f('ix_programa_curso_id'), 'programa_curso', ['id'], unique=False)
    op.create_index(op.f('ix_programa_curso_programa'), 'programa_curso', ['programa'], unique=False)
    op.create_table('slide_show_resource',
    sa.Column('course_id', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['curso.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slide_show_resource_course_id'), 'slide_show_resource', ['course_id'], unique=False)
    op.create_index(op.f('ix_slide_show_resource_id'), 'slide_show_resource', ['id'], unique=False)
    op.create_table('curso_recurso',
    sa.Column('indice', sa.Integer(), nullable=True),
    sa.Column('seccion', sa.String(length=26), nullable=False),
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=1000), nullable=False),
    sa.Column('tipo', sa.String(length=150), nullable=False),
    sa.Column('requerido', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('base_doc_url', sa.String(length=50), nullable=True),
    sa.Column('doc', sa.String(length=50), nullable=True),
    sa.Column('ext', sa.String(length=5), nullable=True),
    sa.Column('text', sa.String(length=750), nullable=True),
    sa.Column('external_code', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['seccion'], ['curso_seccion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ext')
    )
    op.create_index(op.f('ix_curso_recurso_curso'), 'curso_recurso', ['curso'], unique=False)
    op.create_index(op.f('ix_curso_recurso_id'), 'curso_recurso', ['id'], unique=False)
    op.create_index(op.f('ix_curso_recurso_indice'), 'curso_recurso', ['indice'], unique=False)
    op.create_index(op.f('ix_curso_recurso_seccion'), 'curso_recurso', ['seccion'], unique=False)
    op.create_table('estudiante_curso',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=True),
    sa.Column('pago', sa.String(length=26), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['pago'], ['pago.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiante_curso_curso'), 'estudiante_curso', ['curso'], unique=False)
    op.create_index(op.f('ix_estudiante_curso_id'), 'estudiante_curso', ['id'], unique=False)
    op.create_index(op.f('ix_estudiante_curso_pago'), 'estudiante_curso', ['pago'], unique=False)
    op.create_index(op.f('ix_estudiante_curso_usuario'), 'estudiante_curso', ['usuario'], unique=False)
    op.create_table('evaluation',
    sa.Column('section_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_exam', sa.Boolean(), nullable=True),
    sa.Column('passing_score', sa.Float(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('available_until', sa.DateTime(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(), nullable=True),
    sa.Column('reopened_for_user_id', sa.String(length=150), nullable=True),
    sa.Column('penalty_percent', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['reopened_for_user_id'], ['usuario.usuario'], ),
    sa.ForeignKeyConstraint(['section_id'], ['curso_seccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_id'), 'evaluation', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_section_id'), 'evaluation', ['section_id'], unique=False)
    op.create_table('master_class_enrollments',
    sa.Column('master_class_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=150), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('payment_id', sa.String(length=26), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['master_class_id'], ['master_classes.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['pago.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('master_class_id', 'user_id', name='unique_enrollment_per_user')
    )
    op.create_index(op.f('ix_master_class_enrollments_id'), 'master_class_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_master_class_enrollments_master_class_id'), 'master_class_enrollments', ['master_class_id'], unique=False)
    op.create_index(op.f('ix_master_class_enrollments_payment_id'), 'master_class_enrollments', ['payment_id'], unique=False)
    op.create_index(op.f('ix_master_class_enrollments_user_id'), 'master_class_enrollments', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('thread_id', sa.String(length=26), nullable=False),
    sa.Column('sender_id', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_reported', sa.Boolean(), nullable=False),
    sa.Column('reported_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['usuario.usuario'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['message_thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_table('slide',
    sa.Column('slide_show_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['slide_show_id'], ['slide_show_resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slide_id'), 'slide', ['id'], unique=False)
    op.create_index(op.f('ix_slide_slide_show_id'), 'slide', ['slide_show_id'], unique=False)
    op.create_table('curso_recurso_avance',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('recurso', sa.String(length=32), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('requerido', sa.String(length=10), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['recurso'], ['curso_recurso.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_recurso_avance_curso'), 'curso_recurso_avance', ['curso'], unique=False)
    op.create_index(op.f('ix_curso_recurso_avance_id'), 'curso_recurso_avance', ['id'], unique=False)
    op.create_index(op.f('ix_curso_recurso_avance_recurso'), 'curso_recurso_avance', ['recurso'], unique=False)
    op.create_index(op.f('ix_curso_recurso_avance_usuario'), 'curso_recurso_avance', ['usuario'], unique=False)
    op.create_table('curso_recurso_consulta',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('recurso', sa.String(length=32), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('pregunta', sa.String(length=500), nullable=True),
    sa.Column('respuesta', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['recurso'], ['curso_recurso.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_recurso_consulta_id'), 'curso_recurso_consulta', ['id'], unique=False)
    op.create_table('curso_recurso_pregunta',
    sa.Column('indice', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=32), nullable=True),
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('seccion', sa.String(length=32), nullable=False),
    sa.Column('recurso', sa.String(length=32), nullable=False),
    sa.Column('tipo', sa.String(length=15), nullable=True),
    sa.Column('evaluar', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['recurso'], ['curso_recurso.id'], ),
    sa.ForeignKeyConstraint(['seccion'], ['curso_seccion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='curso_recurso_pregunta_unico')
    )
    op.create_index(op.f('ix_curso_recurso_pregunta_curso'), 'curso_recurso_pregunta', ['curso'], unique=False)
    op.create_index(op.f('ix_curso_recurso_pregunta_id'), 'curso_recurso_pregunta', ['id'], unique=False)
    op.create_index(op.f('ix_curso_recurso_pregunta_recurso'), 'curso_recurso_pregunta', ['recurso'], unique=False)
    op.create_index(op.f('ix_curso_recurso_pregunta_seccion'), 'curso_recurso_pregunta', ['seccion'], unique=False)
    op.create_table('curso_recurso_slide_show',
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=True),
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('recurso', sa.String(length=32), nullable=False),
    sa.Column('usuario', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['recurso'], ['curso_recurso.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo', name='codigo_slideshow_unico')
    )
    op.create_index(op.f('ix_curso_recurso_slide_show_curso'), 'curso_recurso_slide_show', ['curso'], unique=False)
    op.create_index(op.f('ix_curso_recurso_slide_show_id'), 'curso_recurso_slide_show', ['id'], unique=False)
    op.create_index(op.f('ix_curso_recurso_slide_show_recurso'), 'curso_recurso_slide_show', ['recurso'], unique=False)
    op.create_table('evaluation_attempt',
    sa.Column('evaluation_id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=150), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('was_late', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_attempt_evaluation_id'), 'evaluation_attempt', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_evaluation_attempt_id'), 'evaluation_attempt', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_attempt_user_id'), 'evaluation_attempt', ['user_id'], unique=False)
    op.create_table('evaluation_reopen_request',
    sa.Column('user_id', sa.String(length=150), nullable=False),
    sa.Column('evaluation_id', sa.String(length=26), nullable=False),
    sa.Column('justification_text', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['usuario.usuario'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_reopen_request_evaluation_id'), 'evaluation_reopen_request', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_evaluation_reopen_request_id'), 'evaluation_reopen_request', ['id'], unique=False)
    op.create_index(op.f('ix_evaluation_reopen_request_user_id'), 'evaluation_reopen_request', ['user_id'], unique=False)
    op.create_table('mensaje',
    sa.Column('usuario', sa.String(length=26), nullable=True),
    sa.Column('curso', sa.String(length=10), nullable=True),
    sa.Column('recurso', sa.String(length=10), nullable=True),
    sa.Column('cerrado', sa.Boolean(), nullable=True),
    sa.Column('publico', sa.Boolean(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('texto', sa.String(length=1000), nullable=True),
    sa.Column('parent', sa.String(length=26), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['parent'], ['mensaje.id'], ),
    sa.ForeignKeyConstraint(['recurso'], ['curso_recurso.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensaje_curso'), 'mensaje', ['curso'], unique=False)
    op.create_index(op.f('ix_mensaje_id'), 'mensaje', ['id'], unique=False)
    op.create_index(op.f('ix_mensaje_parent'), 'mensaje', ['parent'], unique=False)
    op.create_index(op.f('ix_mensaje_recurso'), 'mensaje', ['recurso'], unique=False)
    op.create_index(op.f('ix_mensaje_usuario'), 'mensaje', ['usuario'], unique=False)
    op.create_table('question',
    sa.Column('evaluation_id', sa.String(length=26), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('explanation', sa.String(length=1000), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_evaluation_id'), 'question', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_question_id'), 'question', ['id'], unique=False)
    op.create_table('answer',
    sa.Column('attempt_id', sa.String(length=26), nullable=False),
    sa.Column('question_id', sa.String(length=26), nullable=False),
    sa.Column('selected_option_ids', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['evaluation_attempt.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_attempt_id'), 'answer', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_answer_id'), 'answer', ['id'], unique=False)
    op.create_index(op.f('ix_answer_question_id'), 'answer', ['question_id'], unique=False)
    op.create_table('curso_recurso_pregunta_opcion',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('recurso', sa.String(length=32), nullable=False),
    sa.Column('pregunta', sa.String(length=32), nullable=False),
    sa.Column('texto', sa.String(length=50), nullable=True),
    sa.Column('boleano', sa.Boolean(), nullable=True),
    sa.Column('correcta', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['pregunta'], ['curso_recurso_pregunta.id'], ),
    sa.ForeignKeyConstraint(['recurso'], ['curso_recurso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_recurso_pregunta_opcion_curso'), 'curso_recurso_pregunta_opcion', ['curso'], unique=False)
    op.create_index(op.f('ix_curso_recurso_pregunta_opcion_id'), 'curso_recurso_pregunta_opcion', ['id'], unique=False)
    op.create_index(op.f('ix_curso_recurso_pregunta_opcion_pregunta'), 'curso_recurso_pregunta_opcion', ['pregunta'], unique=False)
    op.create_index(op.f('ix_curso_recurso_pregunta_opcion_recurso'), 'curso_recurso_pregunta_opcion', ['recurso'], unique=False)
    op.create_table('curso_recurso_pregunta_respuesta',
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('recurso', sa.String(length=32), nullable=False),
    sa.Column('pregunta', sa.String(length=32), nullable=False),
    sa.Column('usuario', sa.String(length=150), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=True),
    sa.Column('boleano', sa.Boolean(), nullable=True),
    sa.Column('correcta', sa.Boolean(), nullable=True),
    sa.Column('nota', sa.Float(asdecimal=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['pregunta'], ['curso_recurso_pregunta.id'], ),
    sa.ForeignKeyConstraint(['recurso'], ['curso_recurso.id'], ),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.usuario'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_recurso_pregunta_respuesta_curso'), 'curso_recurso_pregunta_respuesta', ['curso'], unique=False)
    op.create_index(op.f('ix_curso_recurso_pregunta_respuesta_id'), 'curso_recurso_pregunta_respuesta', ['id'], unique=False)
    op.create_index(op.f('ix_curso_recurso_pregunta_respuesta_pregunta'), 'curso_recurso_pregunta_respuesta', ['pregunta'], unique=False)
    op.create_index(op.f('ix_curso_recurso_pregunta_respuesta_recurso'), 'curso_recurso_pregunta_respuesta', ['recurso'], unique=False)
    op.create_index(op.f('ix_curso_recurso_pregunta_respuesta_usuario'), 'curso_recurso_pregunta_respuesta', ['usuario'], unique=False)
    op.create_table('curso_recurso_slides',
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('indice', sa.Integer(), nullable=True),
    sa.Column('curso', sa.String(length=10), nullable=False),
    sa.Column('recurso', sa.String(length=32), nullable=False),
    sa.Column('slide_show', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['curso'], ['curso.codigo'], ),
    sa.ForeignKeyConstraint(['recurso'], ['curso_recurso.id'], ),
    sa.ForeignKeyConstraint(['slide_show'], ['curso_recurso_slide_show.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_recurso_slides_id'), 'curso_recurso_slides', ['id'], unique=False)
    op.create_table('question_option',
    sa.Column('question_id', sa.String(length=26), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('creado', sa.Date(), nullable=False),
    sa.Column('creado_por', sa.String(length=150), nullable=True),
    sa.Column('modificado', sa.DateTime(), nullable=True),
    sa.Column('modificado_por', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_option_id'), 'question_option', ['id'], unique=False)
    op.create_index(op.f('ix_question_option_question_id'), 'question_option', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_option_question_id'), table_name='question_option')
    op.drop_index(op.f('ix_question_option_id'), table_name='question_option')
    op.drop_table('question_option')
    op.drop_index(op.f('ix_curso_recurso_slides_id'), table_name='curso_recurso_slides')
    op.drop_table('curso_recurso_slides')
    op.drop_index(op.f('ix_curso_recurso_pregunta_respuesta_usuario'), table_name='curso_recurso_pregunta_respuesta')
    op.drop_index(op.f('ix_curso_recurso_pregunta_respuesta_recurso'), table_name='curso_recurso_pregunta_respuesta')
    op.drop_index(op.f('ix_curso_recurso_pregunta_respuesta_pregunta'), table_name='curso_recurso_pregunta_respuesta')
    op.drop_index(op.f('ix_curso_recurso_pregunta_respuesta_id'), table_name='curso_recurso_pregunta_respuesta')
    op.drop_index(op.f('ix_curso_recurso_pregunta_respuesta_curso'), table_name='curso_recurso_pregunta_respuesta')
    op.drop_table('curso_recurso_pregunta_respuesta')
    op.drop_index(op.f('ix_curso_recurso_pregunta_opcion_recurso'), table_name='curso_recurso_pregunta_opcion')
    op.drop_index(op.f('ix_curso_recurso_pregunta_opcion_pregunta'), table_name='curso_recurso_pregunta_opcion')
    op.drop_index(op.f('ix_curso_recurso_pregunta_opcion_id'), table_name='curso_recurso_pregunta_opcion')
    op.drop_index(op.f('ix_curso_recurso_pregunta_opcion_curso'), table_name='curso_recurso_pregunta_opcion')
    op.drop_table('curso_recurso_pregunta_opcion')
    op.drop_index(op.f('ix_answer_question_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_id'), table_name='answer')
    op.drop_index(op.f('ix_answer_attempt_id'), table_name='answer')
    op.drop_table('answer')
    op.drop_index(op.f('ix_question_id'), table_name='question')
    op.drop_index(op.f('ix_question_evaluation_id'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_mensaje_usuario'), table_name='mensaje')
    op.drop_index(op.f('ix_mensaje_recurso'), table_name='mensaje')
    op.drop_index(op.f('ix_mensaje_parent'), table_name='mensaje')
    op.drop_index(op.f('ix_mensaje_id'), table_name='mensaje')
    op.drop_index(op.f('ix_mensaje_curso'), table_name='mensaje')
    op.drop_table('mensaje')
    op.drop_index(op.f('ix_evaluation_reopen_request_user_id'), table_name='evaluation_reopen_request')
    op.drop_index(op.f('ix_evaluation_reopen_request_id'), table_name='evaluation_reopen_request')
    op.drop_index(op.f('ix_evaluation_reopen_request_evaluation_id'), table_name='evaluation_reopen_request')
    op.drop_table('evaluation_reopen_request')
    op.drop_index(op.f('ix_evaluation_attempt_user_id'), table_name='evaluation_attempt')
    op.drop_index(op.f('ix_evaluation_attempt_id'), table_name='evaluation_attempt')
    op.drop_index(op.f('ix_evaluation_attempt_evaluation_id'), table_name='evaluation_attempt')
    op.drop_table('evaluation_attempt')
    op.drop_index(op.f('ix_curso_recurso_slide_show_recurso'), table_name='curso_recurso_slide_show')
    op.drop_index(op.f('ix_curso_recurso_slide_show_id'), table_name='curso_recurso_slide_show')
    op.drop_index(op.f('ix_curso_recurso_slide_show_curso'), table_name='curso_recurso_slide_show')
    op.drop_table('curso_recurso_slide_show')
    op.drop_index(op.f('ix_curso_recurso_pregunta_seccion'), table_name='curso_recurso_pregunta')
    op.drop_index(op.f('ix_curso_recurso_pregunta_recurso'), table_name='curso_recurso_pregunta')
    op.drop_index(op.f('ix_curso_recurso_pregunta_id'), table_name='curso_recurso_pregunta')
    op.drop_index(op.f('ix_curso_recurso_pregunta_curso'), table_name='curso_recurso_pregunta')
    op.drop_table('curso_recurso_pregunta')
    op.drop_index(op.f('ix_curso_recurso_consulta_id'), table_name='curso_recurso_consulta')
    op.drop_table('curso_recurso_consulta')
    op.drop_index(op.f('ix_curso_recurso_avance_usuario'), table_name='curso_recurso_avance')
    op.drop_index(op.f('ix_curso_recurso_avance_recurso'), table_name='curso_recurso_avance')
    op.drop_index(op.f('ix_curso_recurso_avance_id'), table_name='curso_recurso_avance')
    op.drop_index(op.f('ix_curso_recurso_avance_curso'), table_name='curso_recurso_avance')
    op.drop_table('curso_recurso_avance')
    op.drop_index(op.f('ix_slide_slide_show_id'), table_name='slide')
    op.drop_index(op.f('ix_slide_id'), table_name='slide')
    op.drop_table('slide')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_master_class_enrollments_user_id'), table_name='master_class_enrollments')
    op.drop_index(op.f('ix_master_class_enrollments_payment_id'), table_name='master_class_enrollments')
    op.drop_index(op.f('ix_master_class_enrollments_master_class_id'), table_name='master_class_enrollments')
    op.drop_index(op.f('ix_master_class_enrollments_id'), table_name='master_class_enrollments')
    op.drop_table('master_class_enrollments')
    op.drop_index(op.f('ix_evaluation_section_id'), table_name='evaluation')
    op.drop_index(op.f('ix_evaluation_id'), table_name='evaluation')
    op.drop_table('evaluation')
    op.drop_index(op.f('ix_estudiante_curso_usuario'), table_name='estudiante_curso')
    op.drop_index(op.f('ix_estudiante_curso_pago'), table_name='estudiante_curso')
    op.drop_index(op.f('ix_estudiante_curso_id'), table_name='estudiante_curso')
    op.drop_index(op.f('ix_estudiante_curso_curso'), table_name='estudiante_curso')
    op.drop_table('estudiante_curso')
    op.drop_index(op.f('ix_curso_recurso_seccion'), table_name='curso_recurso')
    op.drop_index(op.f('ix_curso_recurso_indice'), table_name='curso_recurso')
    op.drop_index(op.f('ix_curso_recurso_id'), table_name='curso_recurso')
    op.drop_index(op.f('ix_curso_recurso_curso'), table_name='curso_recurso')
    op.drop_table('curso_recurso')
    op.drop_index(op.f('ix_slide_show_resource_id'), table_name='slide_show_resource')
    op.drop_index(op.f('ix_slide_show_resource_course_id'), table_name='slide_show_resource')
    op.drop_table('slide_show_resource')
    op.drop_index(op.f('ix_programa_curso_programa'), table_name='programa_curso')
    op.drop_index(op.f('ix_programa_curso_id'), table_name='programa_curso')
    op.drop_index(op.f('ix_programa_curso_curso'), table_name='programa_curso')
    op.drop_table('programa_curso')
    op.drop_index(op.f('ix_pago_usuario'), table_name='pago')
    op.drop_index(op.f('ix_pago_id'), table_name='pago')
    op.drop_index(op.f('ix_pago_curso'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_moderador_curso_usuario'), table_name='moderador_curso')
    op.drop_index(op.f('ix_moderador_curso_id'), table_name='moderador_curso')
    op.drop_index(op.f('ix_moderador_curso_curso'), table_name='moderador_curso')
    op.drop_table('moderador_curso')
    op.drop_index(op.f('ix_message_thread_id'), table_name='message_thread')
    op.drop_table('message_thread')
    op.drop_index(op.f('ix_foro_mensaje_usuario_id'), table_name='foro_mensaje')
    op.drop_index(op.f('ix_foro_mensaje_parent_id'), table_name='foro_mensaje')
    op.drop_index(op.f('ix_foro_mensaje_id'), table_name='foro_mensaje')
    op.drop_index(op.f('ix_foro_mensaje_curso_id'), table_name='foro_mensaje')
    op.drop_table('foro_mensaje')
    op.drop_index(op.f('ix_etiqueta_curso_id'), table_name='etiqueta_curso')
    op.drop_index(op.f('ix_etiqueta_curso_etiqueta'), table_name='etiqueta_curso')
    op.drop_index(op.f('ix_etiqueta_curso_curso'), table_name='etiqueta_curso')
    op.drop_table('etiqueta_curso')
    op.drop_index(op.f('ix_docente_curso_usuario'), table_name='docente_curso')
    op.drop_index(op.f('ix_docente_curso_id'), table_name='docente_curso')
    op.drop_index(op.f('ix_docente_curso_curso'), table_name='docente_curso')
    op.drop_table('docente_curso')
    op.drop_index(op.f('ix_curso_usuario_avance_usuario'), table_name='curso_usuario_avance')
    op.drop_index(op.f('ix_curso_usuario_avance_id'), table_name='curso_usuario_avance')
    op.drop_index(op.f('ix_curso_usuario_avance_curso'), table_name='curso_usuario_avance')
    op.drop_table('curso_usuario_avance')
    op.drop_index(op.f('ix_curso_seccion_indice'), table_name='curso_seccion')
    op.drop_index(op.f('ix_curso_seccion_id'), table_name='curso_seccion')
    op.drop_index(op.f('ix_curso_seccion_curso'), table_name='curso_seccion')
    op.drop_table('curso_seccion')
    op.drop_index(op.f('ix_curso_recurso_descargable_recurso'), table_name='curso_recurso_descargable')
    op.drop_index(op.f('ix_curso_recurso_descargable_id'), table_name='curso_recurso_descargable')
    op.drop_index(op.f('ix_curso_recurso_descargable_curso'), table_name='curso_recurso_descargable')
    op.drop_table('curso_recurso_descargable')
    op.drop_index(op.f('ix_coupon_id'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_created_by'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_course_id'), table_name='coupon')
    op.drop_index(op.f('ix_coupon_code'), table_name='coupon')
    op.drop_table('coupon')
    op.drop_index(op.f('ix_certificacion_usuario'), table_name='certificacion')
    op.drop_index(op.f('ix_certificacion_id'), table_name='certificacion')
    op.drop_index(op.f('ix_certificacion_curso'), table_name='certificacion')
    op.drop_index(op.f('ix_certificacion_certificado'), table_name='certificacion')
    op.drop_table('certificacion')
    op.drop_index(op.f('ix_categoria_curso_id'), table_name='categoria_curso')
    op.drop_index(op.f('ix_categoria_curso_curso'), table_name='categoria_curso')
    op.drop_index(op.f('ix_categoria_curso_categoria'), table_name='categoria_curso')
    op.drop_table('categoria_curso')
    op.drop_index(op.f('ix_announcement_id'), table_name='announcement')
    op.drop_index(op.f('ix_announcement_created_by_id'), table_name='announcement')
    op.drop_index(op.f('ix_announcement_course_id'), table_name='announcement')
    op.drop_table('announcement')
    op.drop_index(op.f('ix_usuario_grupo_miembro_id'), table_name='usuario_grupo_miembro')
    op.drop_table('usuario_grupo_miembro')
    op.drop_index(op.f('ix_master_classes_slug'), table_name='master_classes')
    op.drop_index(op.f('ix_master_classes_instructor_id'), table_name='master_classes')
    op.drop_index(op.f('ix_master_classes_id'), table_name='master_classes')
    op.drop_index(op.f('ix_master_classes_diploma_template_id'), table_name='master_classes')
    op.drop_table('master_classes')
    op.drop_index(op.f('ix_curso_plantilla_certificado'), table_name='curso')
    op.drop_index(op.f('ix_curso_id'), table_name='curso')
    op.drop_index(op.f('ix_curso_estado'), table_name='curso')
    op.drop_index(op.f('ix_curso_codigo'), table_name='curso')
    op.drop_table('curso')
    op.drop_table('blog_post_tags')
    op.drop_index(op.f('ix_blog_comment_user_id'), table_name='blog_comment')
    op.drop_index(op.f('ix_blog_comment_status'), table_name='blog_comment')
    op.drop_index(op.f('ix_blog_comment_post_id'), table_name='blog_comment')
    op.drop_index(op.f('ix_blog_comment_id'), table_name='blog_comment')
    op.drop_table('blog_comment')
    op.drop_index(op.f('ix_usuario_grupo_id'), table_name='usuario_grupo')
    op.drop_index(op.f('ix_usuario_grupo_activo'), table_name='usuario_grupo')
    op.drop_table('usuario_grupo')
    op.drop_index(op.f('ix_recurso_id'), table_name='recurso')
    op.drop_index(op.f('ix_recurso_codigo'), table_name='recurso')
    op.drop_table('recurso')
    op.drop_index(op.f('ix_programa_estudiante_usuario'), table_name='programa_estudiante')
    op.drop_index(op.f('ix_programa_estudiante_programa'), table_name='programa_estudiante')
    op.drop_index(op.f('ix_programa_estudiante_id'), table_name='programa_estudiante')
    op.drop_table('programa_estudiante')
    op.drop_index(op.f('ix_certificado_id'), table_name='certificado')
    op.drop_index(op.f('ix_certificado_code'), table_name='certificado')
    op.drop_table('certificado')
    op.drop_index(op.f('ix_blog_post_status'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_slug'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_id'), table_name='blog_post')
    op.drop_index(op.f('ix_blog_post_author_id'), table_name='blog_post')
    op.drop_table('blog_post')
    op.drop_index(op.f('ix_usuario_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_system_info_param'), table_name='system_info')
    op.drop_table('system_info')
    op.drop_index(op.f('ix_style_id'), table_name='style')
    op.drop_table('style')
    op.drop_index(op.f('ix_programa_id'), table_name='programa')
    op.drop_table('programa')
    op.drop_table('paypal_config')
    op.drop_index(op.f('ix_pagos_config_id'), table_name='pagos_config')
    op.drop_table('pagos_config')
    op.drop_index(op.f('ix_mail_config_id'), table_name='mail_config')
    op.drop_table('mail_config')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_etiqueta_id'), table_name='etiqueta')
    op.drop_table('etiqueta')
    op.drop_index(op.f('ix_configuracion_id'), table_name='configuracion')
    op.drop_table('configuracion')
    op.drop_index(op.f('ix_categoria_id'), table_name='categoria')
    op.drop_table('categoria')
    op.drop_index(op.f('ix_blog_tag_slug'), table_name='blog_tag')
    op.drop_index(op.f('ix_blog_tag_name'), table_name='blog_tag')
    op.drop_index(op.f('ix_blog_tag_id'), table_name='blog_tag')
    op.drop_table('blog_tag')
    op.drop_table('ad_sense')
    # ### end Alembic commands ###
